SELECT YEAR(SALE.SALES_DATE) YEAR, MONTH(SALE.SALES_DATE) MONTH, INFO.GENDER,
(SELECT COUNT(DISTINCT INFO.USER_ID) USERS WHERE GENDER IN (0, 1)) USERS
FROM USER_INFO INFO
JOIN ONLINE_SALE SALE ON INFO.USER_ID = SALE.USER_ID
WHERE GENDER IN (0, 1)
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER