-- 코드를 입력하세요
-- 자동차 종류가 '세단' 또는 'SUV' 인 자동차 중 
-- 2022년 11월 1일부터 2022년 11월 30일까지 대여 가능 
-- 30일간의 대여 금액이 50만원 이상 200만원 미만인 자동차에 대해서 
-- 자동차 ID, 자동차 종류, 대여 금액(컬럼명: FEE) 리스트를 출력
-- 대여 금액을 기준으로 내림차순 정렬, 자동차 종류 오름차순 정렬, 자동차 ID 내림차순

# SELECT CAR.CAR_ID, CAR.CAR_TYPE
SELECT CAR.CAR_ID, CAR.CAR_TYPE, CAR.DAILY_FEE * 30 * (100 - PLAN.DISCOUNT_RATE) DIV 100 AS FEE
FROM CAR_RENTAL_COMPANY_CAR CAR
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY HIS
ON CAR.CAR_ID = HIS.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN PLAN
ON CAR.CAR_TYPE = PLAN.CAR_TYPE
WHERE CAR.CAR_TYPE IN ('세단', 'SUV') AND PLAN.DURATION_TYPE = '30일 이상'
GROUP BY CAR.CAR_ID
HAVING SUM(
    CASE WHEN HIS.HISTORY_ID IN (SELECT HISTORY_ID
                                FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                                WHERE ('2022-11-01' NOT BETWEEN DATE_FORMAT(START_DATE, '%Y-%m-%d') AND DATE_FORMAT(END_DATE, '%Y-%m-%d'))
                                AND ('2022-11-30' NOT BETWEEN DATE_FORMAT(START_DATE, '%Y-%m-%d') AND DATE_FORMAT (END_DATE, '%Y-%m-%d'))) THEN 0
    ELSE 1
    END) = 0
    AND FEE BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC