-- 코드를 입력하세요
SELECT INFO.FOOD_TYPE, INFO.REST_ID, INFO.REST_NAME, INFO.FAVORITES
FROM REST_INFO AS INFO,
(SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
FROM REST_INFO
GROUP BY FOOD_TYPE) AS INFO2
WHERE INFO.FOOD_TYPE = INFO2.FOOD_TYPE AND INFO.FAVORITES = INFO2.FAVORITES
ORDER BY FOOD_TYPE DESC