-- 코드를 입력하세요
# SELECT DATE_FORMAT(ONN.SALES_DATE, '%Y-%m-%d') SALES_DATE, ONN.PRODUCT_ID, ONN.USER_ID, ONN.SALES_AMOUNT
# FROM ONLINE_SALE AS ONN
# LEFT JOIN OFFLINE_SALE AS OFF ON ONN.SALES_DATE = OFF.SALES_DATE
# WHERE ONN.SALES_DATE LIKE '2022-03-%'
# GROUP BY SALES_DATE
# ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC

SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE SALES_DATE LIKE '2022-03-%'
# WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 03
UNION
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE SALES_DATE LIKE '2022-03-%'
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC