-- 코드를 입력하세요
SELECT YEAR(SALE.SALES_DATE) YEAR, MONTH(SALE.SALES_DATE) MONTH, COUNT(DISTINCT SALE.USER_ID) PUCHASED_USERS, ROUND(COUNT(DISTINCT SALE.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE JOINED LIKE '2021%'), 1) PUCHASED_RATIO
FROM USER_INFO INFO
JOIN ONLINE_SALE SALE ON INFO.USER_ID = SALE.USER_ID
WHERE JOINED LIKE '2021%'
GROUP BY YEAR(SALE.SALES_DATE), MONTH(SALE.SALES_DATE)
ORDER BY YEAR, MONTH