# -- 코드를 입력하세요

SET @HOUR = -1; # 변수선언, 맨 뒤에 ';' 꼭 찍어주기

SELECT (@HOUR := @HOUR + 1) AS HOUR,
(SELECT COUNT(*) FROM ANIMAL_OUTS WHERE HOUR(DATETIME) = @HOUR) AS COUNT 
FROM ANIMAL_OUTS
WHERE @HOUR < 23