-- 코드를 입력하세요
SELECT FLAVOR
FROM (SELECT FLAVOR, SUM(TOTAL_ORDER) AS AMOUNT
     FROM FIRST_HALF
     GROUP BY FLAVOR 
     UNION ALL
     SELECT FLAVOR, SUM(TOTAL_ORDER)
     FROM JULY
     GROUP BY FLAVOR) AS TEMP
GROUP BY FLAVOR
ORDER BY SUM(AMOUNT) DESC
LIMIT 3;
