-- 코드를 입력하세요
# SELECT U.USER_ID, U.NICKNAME, B.PRICE AS TOTAL_SALES FROM USED_GOODS_BOARD B
# JOIN USED_GOODS_USER U ON B.WRITER_ID = U.USER_ID
# WHERE B.STATUS LIKE 'DONE'
# GROUP BY TOTAL_SALES HAVING SUM(TOTAL_SALES) >= 700000
# ORDER BY TOTAL_SALES ASC

SELECT U.USER_ID, U.NICKNAME, SUM(B.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS B
JOIN USED_GOODS_USER AS U ON B.WRITER_ID = U.USER_ID
WHERE B.STATUS = 'DONE'
GROUP BY USER_ID HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES ASC