# -- 코드를 작성해주세요
# SELECT T1.FISH_COUNT, FISH_NAME_INFO.FISH_NAME
# FROM (
#     SELECT FISH_TYPE, COUNT(FISH_TYPE) AS FISH_COUNT
#     FROM FISH_INFO
#     GROUP BY FISH_TYPE
# ) T1
# JOIN FISH_NAME_INFO 
# ON T1.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
# ORDER BY T1.FISH_COUNT DESC

SELECT COUNT(ID) AS FISH_COUNT, FISH_NAME
FROM FISH_INFO F1
JOIN FISH_NAME_INFO F2
ON F1.FISH_TYPE = F2.FISH_TYPE
GROUP BY FISH_NAME
ORDER BY FISH_COUNT DESC