-- 코드를 입력하세요
SELECT BOOK.CATEGORY, SUM(BOOK_SALES.SALES) AS TOTAL_SALES
FROM BOOK, BOOK_SALES
WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 01
AND BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
GROUP BY CATEGORY
ORDER BY CATEGORY ASC