-- 코드를 입력하세요
SELECT AUTHOR.AUTHOR_ID, AUTHOR.AUTHOR_NAME, BOOK.CATEGORY,
SUM(BOOK.PRICE * SALES.SALES) TOTAL_SALES FROM BOOK
JOIN AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
JOIN BOOK_SALES SALES ON BOOK.BOOK_ID = SALES.BOOK_ID
WHERE SALES.SALES_DATE LIKE '2022-01%'
GROUP BY BOOK.CATEGORY, AUTHOR.AUTHOR_ID
ORDER BY AUTHOR.AUTHOR_ID ASC, BOOK.CATEGORY DESC
