-- 코드를 입력하세요
SELECT BOARD.TITLE, BOARD.BOARD_ID, REPLY.REPLY_ID, REPLY.WRITER_ID, REPLY.CONTENTS, DATE_FORMAT(REPLY.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_REPLY REPLY
JOIN USED_GOODS_BOARD BOARD ON BOARD.BOARD_ID = REPLY.BOARD_ID
WHERE BOARD.CREATED_DATE BETWEEN '2022-10-01' AND '2022-10-31'
ORDER BY REPLY.CREATED_DATE ASC, BOARD.TITLE ASC



# SELECT b.TITLE, b.BOARD_ID, r.REPLY_ID, r.WRITER_ID, r.CONTENTS, DATE_FORMAT(r.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
# FROM USED_GOODS_BOARD b
# JOIN USED_GOODS_REPLY r ON b.BOARD_ID = r.BOARD_ID
# WHERE b.CREATED_DATE BETWEEN '2022-10-01' AND '2022-10-31'
# ORDER BY r.CREATED_DATE ASC, b.TITLE ASC;