-- 코드를 작성해주세요

SELECT C.ITEM_ID, ITEM_NAME, RARITY
FROM (
    SELECT B.ITEM_ID
    FROM ITEM_INFO A
    LEFT JOIN ITEM_TREE B
    ON A.ITEM_ID = B.PARENT_ITEM_ID
    WHERE A.RARITY = 'RARE' AND B.PARENT_ITEM_ID IS NOT NULL
    ) C
LEFT JOIN ITEM_INFO
ON C.ITEM_ID = ITEM_INFO.ITEM_ID
ORDER BY 1 DESC