-- 코드를 작성해주세요
SELECT DISTINCT(ID), EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
JOIN (
    SELECT *
    FROM SKILLCODES
    WHERE NAME = 'Python' OR NAME = 'C#'
    ) AS SKILL
ON (DEVELOPERS.SKILL_CODE & SKILL.CODE) = SKILL.CODE
ORDER BY ID