-- 코드를 작성해주세요
SELECT G.SCORE, G.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_DEPARTMENT AS D
JOIN HR_EMPLOYEES AS E
ON D.DEPT_ID = E.DEPT_ID
JOIN (
    SELECT EMP_NO, SCORE, RANK() OVER (ORDER BY SCORE DESC) AS RANKING
    FROM (
        SELECT EMP_NO, SUM(SCORE) AS SCORE
        FROM HR_GRADE
        WHERE YEAR = 2022
        GROUP BY EMP_NO
    ) AS TEMP
) AS G
ON E.EMP_NO = G.EMP_NO
WHERE G.RANKING = 1
ORDER BY G.SCORE DESC

# SELECT G.SCORE, G.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
# FROM HR_DEPARTMENT AS D
# JOIN HR_EMPLOYEES AS E
# ON D.DEPT_ID = E.DEPT_ID
# JOIN (
#     SELECT EMP_NO, SUM(SCORE) AS SCORE
#     FROM HR_GRADE AS TEMP
#     WHERE YEAR = 2022
#     GROUP BY EMP_NO
# ) AS G
# ON E.EMP_NO = G.EMP_NO
# ORDER BY G.SCORE DESC
# LIMIT 1